environment = "staging"
project_id = "template-backend-staging"
github_owner = "fddiferd"
github_repo = "template-backend"
user_email = "fddiferd@gmail.com"
region = "us-central1"
service_name = "template-api"
repo_name = "template-backend"
