# This file is automatically generated by bootstrap.sh
# Do not edit manually
environment = "dev"
billing_account_id = ""
project_ids = {
  dev = "template-backend-dev-fddiferd"
}
region = "us-central1"
service_name = "template-api"
repo_name = "template-backend"
